### PR TITLE
Add the ability to specify dogbones along longest or shortest side of a mortise

### PR DESCRIPTION
**Pull request by DVE2000**
I think the title says it all. I think Dogbone is a pretty cool add-in. There's one comment in my code where I commented out a constraint. I don't think the constraint is required, but I figured I should point this out.

### CODE REVIEW

**Comment by caseycrogers** [comment]
He DVE-glad to see someone working on this project! I've largely stopped managing it. I've ,merged your request-if you want I can give you management privileges for the repo. Let me know if you want them.

**Comment by DVE2000** [comment]
Thanks, Casey! Yeah, I'd like management privileges, please. I made a couple of releases today, because someone found a bug.

Edit: Ah, I see you merged everything in. I guess having management privileges would still be good, in case we find anything else. Or I add new features.

**Comment by caseycrogers** [comment]
Just added you as a collaborator. You should have an invite in your e-mail!

**Comment by DVE2000** [comment]
Got it. Thanks!

**Pull request merged**
